Make the string to be searched in seed status more specific

diff --git a/pkc b/pkc
--- a/pkc
+++ b/pkc
@@ -114,8 +114,8 @@ seed_eauth() {
         # Restarting the Eauth server so that it can finally have access to the DB.
         sudo docker exec -it micro-pkc_eauth_1 pkill node
         sleep 4
-        seed_status=$(sudo docker exec -it micro-pkc_eauth_1 sh -c 'npx sequelize-cli db:seed:all && echo "pass" || echo "fail"')
-        if  [[ "$seed_status" == *pass* ]]; then
+        seed_status=$(sudo docker exec -it micro-pkc_eauth_1 sh -c 'npx sequelize-cli db:seed:all && echo "passYAY" || echo "fail"')
+        if  [[ "$seed_status" == *passYAY* ]]; then
             break
         fi
         echo "Retrying to seed Eauth DB again ..."
