Close issue 125: harden favicon download in script

diff --git a/pkc b/pkc
--- a/pkc
+++ b/pkc
@@ -330,7 +330,17 @@ run_setup() {
 
     # We always download the favicon fresh, so that it is always up to date.
     echo "Downloading browser favicon"
-    sudo docker exec micro-pkc-mediawiki curl https://raw.githubusercontent.com/inblockio/aqua-branding/main/logos/aqua-white-1024x1024-32x32.png -o favicon.ico
+
+    # Setting a timeout for the curl command and redirecting stderr to stdout to handle both output and error
+    if timeout 15 sudo docker exec micro-pkc-mediawiki bash -c "curl https://raw.githubusercontent.com/inblockio/aqua-branding/main/logos/aqua-white-1024x1024-32x32.png -o favicon.ico 2>&1"; then
+        echo "Download favicon successful."
+    else
+        # This block executes if curl fails due to timeout or any other reason
+        case $? in
+            124) echo "Favicon download failed after 15 seconds (time out)." ;;
+            *) echo "The command failed for a different reason." ;;
+        esac
+    fi
 
     # Prepare auto backup
     sudo cp aqua/do_backup_wrapper.sh mountPoint/backup
