refactor: Use docker compose instead of docker-compose

diff --git a/pkc b/pkc
--- a/pkc
+++ b/pkc
@@ -69,9 +69,9 @@ check_dependencies() {
         exit 1
     fi
 
-    # Check docker-compose installation
-    if ! which docker-compose; then
-        echo "Error: docker-compose is not yet installed. Aborting PKC installation." >&2
+    # Check docker compose installation
+    if $(docker compose &>/dev/null) && [ $? -ne 0 ]; then
+        echo "Error: docker compose is not yet installed. Aborting PKC installation." >&2
         exit 1
     fi
 
@@ -146,11 +146,11 @@ validate_web_public_detail() {
 
 setup_proxy_server() {
     echo "Setting up Nginx proxy server with Let's Encrypt"
-    docker-compose -f proxy_server/docker-compose.yml up -d
+    docker compose -f proxy_server/docker-compose.yml up -d
     echo "Ensuring that the Nginx server allows 100 MB file upload"
     # See https://github.com/nginx-proxy/nginx-proxy/issues/981#issuecomment-345434827
     docker exec proxy_server_proxy_1 sh -c 'echo "client_max_body_size 100M;" > /etc/nginx/conf.d/custom_proxy_settings.conf'
-    docker-compose -f proxy_server/docker-compose.yml restart proxy
+    docker compose -f proxy_server/docker-compose.yml restart proxy
     echo "Sleeping for 3s 💤 💤"
     sleep 3
     echo "Proxy setup done!"
@@ -174,11 +174,11 @@ prepare_dotenv() {
 
 do_docker_compose_up_maybe_backup() {
     if [ "$web_public" = true ]; then
-      docker-compose -f docker-compose-web.yml pull
-      docker-compose -f docker-compose-web.yml up -d
+      docker compose -f docker-compose-web.yml pull
+      docker compose -f docker-compose-web.yml up -d
     else
-      docker-compose -f docker-compose-local.yml pull
-      docker-compose -f docker-compose-local.yml up -d
+      docker compose -f docker-compose-local.yml pull
+      docker compose -f docker-compose-local.yml up -d
     fi
     if [ -f .autobackup ]; then
         echo "Starting cron for auto-backup"
@@ -289,7 +289,7 @@ run_setup() {
     perl -i -p -e "s|PKC_SERVER|$PKC_SERVER|" .env
 	perl -i -p -e "s|SIWEOIDC_SERVER|$SIWEOIDC_SERVER|" .env
 
-    echo "Executing docker-compose up -d. Be prepared to type your password."
+    echo "Executing docker compose up -d. Be prepared to type your password."
     # Support version 1 / 2 of docker-compose
     do_docker_compose_up_maybe_backup
     # Sleep; just to be sure that the container has initialized well.
@@ -364,11 +364,11 @@ stop_container() {
     cp .env.template .env
   fi
   if [[ $(docker network ls | grep proxy_server_net ) ]]; then
-    docker-compose -f docker-compose-web.yml down
+    docker compose -f docker-compose-web.yml down
 #    proxy only runs in web deployment
-    docker-compose -f proxy_server/docker-compose.yml down
+    docker compose -f proxy_server/docker-compose.yml down
   else
-    docker-compose -f docker-compose-local.yml down
+    docker compose -f docker-compose-local.yml down
   fi
   if [ "$env_existed" = false ]; then
     rm .env
@@ -427,7 +427,7 @@ while [[ $# -gt 0 ]]; do
             most_recent=$(ls -t mountPoint/backup/*.tar.gz | head -n 1 | xargs basename)
             restore_all "$most_recent"
             # A reset is required to flush outdated cache from the system.
-            docker-compose stop
+            docker compose stop
             do_docker_compose_up_maybe_backup
             break
             ;;
